### PR TITLE
Fix test failure due to comparing floats

### PR DESCRIPTION
**Pull request by samebchase**
We get test failures of the form:

"LOG10(2)" evaluated to 0.30102999566398114d0
which is not EQUAL to 0.3010299956639812d0

which is due to comparing floats.

We relax this by using a tolerance value by which floats are considered to be equal.

Pull Requests are only accepted from signed contributors:

* [x] Read `CONTRIBUTING.md`
* [x] Sign the Endatabas Contributor Agreement

Thank you for your understanding.

### CODE REVIEW

**Comment by deobald** [comment]
@samebchase Perhaps I'm misunderstanding the logic of `%float-approximately-equalp`... is `equality-helpers` supposed to provide single- and double-digit tolerances, as in your patch, instead of 15- or 16-digit tolerances? (ex. `0.0000000000000001`)

**Comment by samebchase** [comment]
@deobald My understanding was that, comparing floats for equality is unpredictable and error prone. For example there's no way of guaranteeing that 1.23 == 1.23 will return true.

We need to have some approximate comparison for floats. Now by default I used 1e-5 as the tolerance. We can optionally pass a more fime grained tolerance value.

This is a naive (and commonly used) approach for comparing floats. There are more sophisticated ones where the tolerance value is scaled based on the size of the floats, let find that implementation, but for now it should be okay.

**Comment by deobald** [comment]
@samebchase The default of `1e-5` seems fine, but isn't it overridden with `0.1` and `0.01` in `equality-helpers`?

**Comment by samebchase** [comment]
@deobald It's an optional arg. If nothing is passed it will default to `1e-5`. For the `equality-helper` tests, I used a much larger tolerance value. 

In the actual tests, I am not passing in any value, so the default will kick in.

**Comment by samebchase** [comment]
Closing this.

**Pull request closed without merging**
